# Generated by Django 6.0.4 on 2026-04-12 22:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_remove_offer_uniq_offer_link_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapingJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("source_domain", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("paused", "Paused")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("run_interval_minutes", models.PositiveIntegerField(default=360)),
                ("use_llm_fallback", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "scraping_job",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="ScrapingRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_key", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("offers_processed", models.PositiveIntegerField(default=0)),
                ("offers_created", models.PositiveIntegerField(default=0)),
                ("offers_updated", models.PositiveIntegerField(default=0)),
                ("offers_unchanged", models.PositiveIntegerField(default=0)),
                ("offers_flagged_stale", models.PositiveIntegerField(default=0)),
                ("offers_deleted", models.PositiveIntegerField(default=0)),
                ("llm_calls_count", models.PositiveIntegerField(default=0)),
                ("errors_count", models.PositiveIntegerField(default=0)),
                ("log", models.JSONField(default=list)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="content.scrapingjob",
                    ),
                ),
            ],
            options={
                "db_table": "scraping_run",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="idx_scraping_run_status"),
                    models.Index(
                        fields=["source_key", "-created_at"],
                        name="idx_scraping_run_source",
                    ),
                ],
            },
        ),
    ]
