# Generated by Django 6.0.4 on 2026-04-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_scrapingjob_scrapingrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="user",
            name="profile",
            field=models.CharField(
                choices=[
                    ("Student", "Student"),
                    ("Academic staff", "Academic staff"),
                    ("Company", "Company"),
                ],
                default="Student",
                max_length=30,
            ),
        ),
    ]
