# Generated by Django 6.0.4 on 2026-05-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_merge_user_profile_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(choices=[('Student', 'Student'), ('Academic staff', 'Academic staff'), ('Company', 'Company'), ('Admin', 'Admin')], default='Student', max_length=30),
        ),
    ]
