# Generated by Django 6.0.4 on 2026-05-15 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_user_admin_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userneed',
            name='target_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_needs', to='content.targetprofile'),
        ),
    ]
