from content.scrapers.types import SourceDefinition


SOURCE_REGISTRY: list[SourceDefinition] = [
    SourceDefinition(
        key="unibz_master_software_engineering",
        name="UNIBZ Master in Software Engineering",
        url="https://www.unibz.it/en/faculties/engineering/master-software-engineering/",
        organization_token="unibz",
        target_profile="student",
        country="IT",
        domain_names=["AI", "Digitalisation", "Technology_transfer"],
    ),
    SourceDefinition(
        key="unibz_phd_computer_science",
        name="UNIBZ PhD in Computer Science",
        url="https://www.unibz.it/en/faculties/engineering/phd-computer-science/",
        organization_token="unibz",
        target_profile="researcher",
        country="IT",
        domain_names=["AI", "Digitalisation"],
    ),
    SourceDefinition(
        key="unibz_bachelor_computer_science",
        name="UNIBZ Bachelor in Computer Science",
        url="https://www.unibz.it/en/faculties/engineering/bachelor-computer-science/",
        organization_token="unibz",
        target_profile="student",
        country="IT",
        domain_names=["Digitalisation", "Cybersecurity"],
    ),
    SourceDefinition(
        key="unibz_erasmus_mobility",
        name="UNIBZ International Mobility",
        url="https://www.unibz.it/en/applicants/international/",
        organization_token="unibz",
        target_profile="student",
        country="IT",
        domain_names=["Mobility", "Digitalisation"],
    ),
    SourceDefinition(
        key="mdu_fas_licentiate_thesis",
        name="MDU Research Schools Thesis Track",
        url="https://www.mdu.se/en/malardalen-university/research/research-schools",
        organization_token="mdu",
        target_profile="researcher",
        country="SE",
        domain_names=["Robotics", "AI"],
    ),
    SourceDefinition(
        key="mdu_embedded_systems_research_group",
        name="MDU Embedded Systems Research Group",
        url="https://www.mdu.se/en/malardalen-university/research/research-specialisations/embedded-systems",
        organization_token="mdu",
        target_profile="researcher",
        country="SE",
        domain_names=["Robotics", "AI"],
    ),
    SourceDefinition(
        key="mdu_din_funding_partner",
        name="MDU DIN Funding Partner",
        url="https://www.mdu.se/en/malardalen-university/research/research-specialisations/innovation-and-product-realisation",
        organization_token="mdu",
        target_profile="company",
        country="SE",
        domain_names=["Technology_transfer", "Innovation_and_entrepreneurship"],
    ),
    SourceDefinition(
        key="tu_ilmenau_crawler_seed",
        name="TU Ilmenau Crawler Seed",
        url="https://www.tu-ilmenau.de/",
        organization_token="tu_ilmenau",
        target_profile="student",
        country="DE",
        domain_names=["Digitalisation"],
        enabled=True,
        crawl_enabled=True,
        crawl_depth=3,
        crawl_max_pages=100,
        crawl_match_patterns=["/en/", "/studium/studiengaenge", "/forschung/"],
        crawl_exclude_patterns=["/studium/vor-dem-studium", "/news", "/events", "/presse", "/veranstaltungen", "/forschung-international/sunrise"],
    ),
    SourceDefinition(
        key="unibz_crawler_seed",
        name="UNIBZ Crawler Seed",
        url="https://www.unibz.it/",
        organization_token="unibz",
        target_profile="student",
        country="IT",
        domain_names=["Digitalisation"],
        enabled=True,
        crawl_enabled=True,
        crawl_depth=3,
        crawl_max_pages=100,
        crawl_match_patterns=["/en/", "/faculties/", "/applicants/"],
        crawl_exclude_patterns=[
            "/en/home/",
            "/news", "/events", "/contact", "/alumni",
            "/sustainability", "/quality-assurance",
            "/assignments", "/position-calls", "/5x1000",
            "/companies-and-partnerships",
        ],
    ),
    SourceDefinition(
        key="uitm_crawler_seed",
        name="UITM Crawler Seed",
        url="https://www.uitm.edu.eu/",
        organization_token="uitm",
        target_profile="student",
        country="PL",
        domain_names=["Digitalisation"],
        enabled=True,
        crawl_enabled=True,
        crawl_depth=3,
        crawl_max_pages=100,
        crawl_match_patterns=["/en/", "/study", "/research"],
        crawl_exclude_patterns=["/contact", "/news", "/events", "/login", "/apply", "/gallery", "/awards", "/alumni", "/press", "/donate"],
    ),
    SourceDefinition(
        key="utc_crawler_seed",
        name="UTC Crawler Seed",
        url="https://www.utc.fr/",
        organization_token="utc",
        target_profile="student",
        country="FR",
        domain_names=["Digitalisation"],
        enabled=True,
        crawl_enabled=True,
        crawl_depth=3,
        crawl_max_pages=100,
        crawl_match_patterns=["/en/", "/formation", "/recherche"],
        crawl_exclude_patterns=["/contact", "/news", "/events", "/login", "/apply", "/actualites", "/agenda", "/alumni", "/presse"],
    ),
    SourceDefinition(
        key="euc_crawler_seed",
        name="European University Cyprus Crawler Seed",
        url="https://www.euc.ac.cy/",
        organization_token="euc",
        target_profile="student",
        country="CY",
        domain_names=["Digitalisation"],
        enabled=True,
        crawl_enabled=True,
        crawl_depth=3,
        crawl_max_pages=100,
        crawl_match_patterns=["/en/programs", "/en/research", "/en/schools", "/en/faculties"],
        crawl_exclude_patterns=["/contact", "/apply", "/login", "/news", "/events", "/gallery", "/awards", "/recognition"],
    ),
    SourceDefinition(
        key="mdu_crawler_seed",
        name="MDU Crawler Seed",
        url="https://www.mdu.se/",
        organization_token="mdu",
        target_profile="student",
        country="SE",
        domain_names=["Digitalisation"],
        enabled=True,
        crawl_enabled=True,
        crawl_depth=3,
        crawl_max_pages=100,
        crawl_match_patterns=["/en/", "/forskning", "/utbildning"],
        crawl_exclude_patterns=["/contact", "/news", "/events", "/login", "/apply", "/nyheter", "/evenemang", "/alumni", "/press", "/donate", "/calendar", "/konferens"],
    ),
    SourceDefinition(
        key="univpm_crawler_seed",
        name="UNIVPM Crawler Seed",
        url="https://www.univpm.it/",
        organization_token="univpm",
        target_profile="student",
        country="IT",
        domain_names=["Digitalisation"],
        enabled=True,
        crawl_enabled=True,
        crawl_depth=3,
        # /En/ is a 404 redirect — use only the working Italian /Entra/ section
        crawl_match_patterns=["/Entra/", "/Didattica", "/Ricerca"],
        crawl_exclude_patterns=["/Contact", "/News", "/Events", "/Login", "/Apply", "/Notizie", "/Calendario", "/Alumni", "/Press"],
    ),
    SourceDefinition(
        key="unmo_crawler_seed",
        name="UNMO Crawler Seed",
        url="https://www.unmo.ba/",
        organization_token="unmo",
        target_profile="student",
        country="BA",
        domain_names=["Digitalisation"],
        enabled=True,
        crawl_enabled=True,
        crawl_depth=2,
        crawl_match_patterns=["/en/", "/nastava", "/istrazivanje"],
        crawl_exclude_patterns=["/contact", "/news", "/events", "/login", "/apply", "/vijesti", "/alumni", "/press"],
    ),
    SourceDefinition(
        key="ipvc_crawler_seed",
        name="IPVC Crawler Seed",
        url="https://www.ipvc.pt/",
        organization_token="ipvc",
        target_profile="student",
        country="PT",
        domain_names=["Digitalisation"],
        enabled=True,
        crawl_enabled=True,
        crawl_depth=3,
        crawl_match_patterns=["/en/", "/cursos", "/investigacao"],
        crawl_exclude_patterns=[
            "/contact", "/news", "/events", "/login", "/apply",
            "/noticias", "/agenda", "/alumni", "/imprensa",
            "/sobre-o-ipvc/", "/organizacao/",
            "/orcamento", "/contratos-publicos", "/projetos-institucionais",
            "/servicos/", "/escolas-ipvc/", "/gabinete", "/clipping",
        ],
    ),


    # ── TU Ilmenau targeted seeds ─────────────────────────────────────────
    SourceDefinition(
        key="tu_ilmenau_karriere",
        name="TU Ilmenau Scientific Career",
        url="https://www.tu-ilmenau.de/forschung/wissenschaftliche-karriere/",
        organization_token="tu_ilmenau",
        target_profile="researcher",
        country="DE",
        domain_names=["AI", "Digitalisation"],
        crawl_enabled=True,
        crawl_depth=2,
        crawl_match_patterns=["/forschung/wissenschaftliche-karriere/"],
        crawl_exclude_patterns=["/news", "/presse", "/veranstaltungen"],
    ),
    SourceDefinition(
        key="tu_ilmenau_industry",
        name="TU Ilmenau Industry Collaboration",
        url="https://www.tu-ilmenau.de/forschung/wirtschaft-und-transfer/zusammenarbeit-mit-der-tu-ilmenau",
        organization_token="tu_ilmenau",
        target_profile="company",
        country="DE",
        domain_names=["Technology_transfer", "Innovation_and_entrepreneurship"],
        crawl_enabled=True,
        crawl_depth=2,
        crawl_match_patterns=["/forschung/wirtschaft-und-transfer/"],
        crawl_exclude_patterns=["/news", "/presse", "/veranstaltungen"],
    ),
    SourceDefinition(
        key="tu_ilmenau_degree_programmes",
        name="TU Ilmenau Degree Programmes",
        url="https://www.tu-ilmenau.de/en/study/degree-programmes",
        organization_token="tu_ilmenau",
        target_profile="student",
        country="DE",
        domain_names=["Digitalisation", "AI"],
        crawl_enabled=True,
        crawl_depth=2,
        crawl_match_patterns=["/en/study/", "/studium/studiengaenge"],
        crawl_exclude_patterns=["/news", "/presse", "/veranstaltungen", "/vor-dem-studium"],
    ),
    SourceDefinition(
        key="tu_ilmenau_transfer",
        name="TU Ilmenau Transfer & Region",
        url="https://www.tu-ilmenau.de/forschung/wirtschaft-und-transfer/transfer-und-region",
        organization_token="tu_ilmenau",
        target_profile="company",
        country="DE",
        domain_names=["Technology_transfer"],
        crawl_enabled=True,
        crawl_depth=2,
        crawl_match_patterns=["/forschung/wirtschaft-und-transfer/"],
        crawl_exclude_patterns=["/news", "/presse"],
    ),

    # ── UTC targeted seeds ────────────────────────────────────────────────
    SourceDefinition(
        key="utc_formations_ingenieur",
        name="UTC Engineering Programmes",
        url="https://www.utc.fr/formations/ingenieur/",
        organization_token="utc",
        target_profile="student",
        country="FR",
        domain_names=["Digitalisation", "AI"],
        enabled=False,  # 404 — URL returns not-found
        crawl_enabled=True,
        crawl_depth=2,
        crawl_match_patterns=["/formations/ingenieur/"],
        crawl_exclude_patterns=["/actualites", "/agenda", "/contact"],
    ),
    SourceDefinition(
        key="utc_formations_master",
        name="UTC Master Programmes",
        url="https://www.utc.fr/formations/master/",
        organization_token="utc",
        target_profile="student",
        country="FR",
        domain_names=["Digitalisation"],
        crawl_enabled=True,
        crawl_depth=2,
        crawl_match_patterns=["/formations/master/"],
        crawl_exclude_patterns=["/actualites", "/agenda", "/contact"],
    ),
    SourceDefinition(
        key="utc_recherche_unites",
        name="UTC Research Units",
        url="https://www.utc.fr/recherche/les-unites-de-recherche-de-lutc/",
        organization_token="utc",
        target_profile="researcher",
        country="FR",
        domain_names=["AI", "Digitalisation"],
        crawl_enabled=True,
        crawl_depth=2,
        crawl_match_patterns=["/recherche/"],
        crawl_exclude_patterns=["/actualites", "/agenda", "/contact", "/innovation-technologique"],
    ),
    SourceDefinition(
        key="utc_apprentissage",
        name="UTC Apprenticeship",
        url="https://www.utc.fr/formations/apprentissage/",
        organization_token="utc",
        target_profile="student",
        country="FR",
        domain_names=["Digitalisation", "Technology_transfer"],
        crawl_enabled=True,
        crawl_depth=2,
        crawl_match_patterns=["/formations/"],
        crawl_exclude_patterns=["/actualites", "/agenda", "/contact", "/candidater"],
    ),

    # ── UNIVPM Italian targeted seeds ────────────────────────────────────
    SourceDefinition(
        key="univpm_didattica",
        name="UNIVPM Didattica (Courses)",
        url="https://www.univpm.it/Entra/Didattica",
        organization_token="univpm",
        target_profile="student",
        country="IT",
        domain_names=["Digitalisation", "AI"],
        crawl_enabled=True,
        crawl_depth=2,
        crawl_match_patterns=["/Entra/Didattica"],
        crawl_exclude_patterns=["/Notizie", "/Calendario", "/Contatti", "/HR_Excellence"],
    ),
    SourceDefinition(
        key="univpm_ricerca",
        name="UNIVPM Ricerca (Research)",
        url="https://www.univpm.it/Entra/Ricerca",
        organization_token="univpm",
        target_profile="researcher",
        country="IT",
        domain_names=["AI", "Digitalisation"],
        crawl_enabled=True,
        crawl_depth=2,
        crawl_match_patterns=["/Entra/Ricerca"],
        crawl_exclude_patterns=["/Notizie", "/Calendario", "/Contatti", "/HR_Excellence"],
    ),
    SourceDefinition(
        key="univpm_terza_missione",
        name="UNIVPM Terza Missione (Innovation & Transfer)",
        url="https://www.univpm.it/Entra/Terza_Missione",
        organization_token="univpm",
        target_profile="company",
        country="IT",
        domain_names=["Innovation", "Digitalisation"],
        enabled=False,  # 404 — URL returns not-found
        crawl_enabled=True,
        crawl_depth=2,
        crawl_match_patterns=["/Entra/Terza_Missione"],
        crawl_exclude_patterns=["/Notizie", "/Calendario", "/Contatti"],
    ),

    # ── EUC targeted seeds ────────────────────────────────────────────────
    SourceDefinition(
        key="euc_postgraduate",
        name="EUC Postgraduate Programs",
        url="https://www.euc.ac.cy/en/programs/postgraduate/",
        organization_token="euc",
        target_profile="student",
        country="CY",
        domain_names=["Digitalisation", "AI"],
        crawl_enabled=True,
        crawl_depth=2,
        crawl_match_patterns=["/en/programs/"],
        crawl_exclude_patterns=["/contact", "/apply", "/news", "/events"],
    ),
    SourceDefinition(
        key="euc_research_centres",
        name="EUC Research Centres",
        url="https://www.euc.ac.cy/en/research/research-centres/",
        organization_token="euc",
        target_profile="researcher",
        country="CY",
        domain_names=["AI", "Digitalisation"],
        enabled=False,  # 404 — non-www URL not found
        crawl_enabled=True,
        crawl_depth=2,
        crawl_match_patterns=["/en/research/"],
        crawl_exclude_patterns=["/contact", "/apply", "/news", "/events"],
    ),
    SourceDefinition(
        key="euc_schools",
        name="EUC Schools & Faculties",
        url="https://www.euc.ac.cy/en/schools/",
        organization_token="euc",
        target_profile="student",
        country="CY",
        domain_names=["Digitalisation"],
        crawl_enabled=True,
        crawl_depth=2,
        crawl_match_patterns=["/en/schools/", "/en/faculties/"],
        crawl_exclude_patterns=["/contact", "/apply", "/news", "/events"],
    ),

    # ── UITM targeted seeds ───────────────────────────────────────────────
    SourceDefinition(
        key="uitm_studies",
        name="UITM Studies",
        url="https://www.uitm.edu.eu/en/studies/",
        organization_token="uitm",
        target_profile="student",
        country="PL",
        domain_names=["Digitalisation", "AI"],
        crawl_enabled=True,
        crawl_depth=2,
        crawl_match_patterns=["/en/studies/", "/en/study"],
        crawl_exclude_patterns=["/contact", "/news", "/events", "/login", "/apply"],
    ),
    SourceDefinition(
        key="uitm_research",
        name="UITM Research",
        url="https://www.uitm.edu.eu/en/research/",
        organization_token="uitm",
        target_profile="researcher",
        country="PL",
        domain_names=["AI", "Digitalisation"],
        crawl_enabled=True,
        crawl_depth=2,
        crawl_match_patterns=["/en/research/"],
        crawl_exclude_patterns=["/contact", "/news", "/events", "/login"],
    ),


    # ── IPVC targeted seeds ───────────────────────────────────────────────
    SourceDefinition(
        key="ipvc_courses",
        name="IPVC Courses",
        url="https://www.ipvc.pt/en/cursos/",
        organization_token="ipvc",
        target_profile="student",
        country="PT",
        domain_names=["Digitalisation"],
        crawl_enabled=True,
        crawl_depth=2,
        crawl_match_patterns=["/en/cursos/", "/en/courses/"],
        crawl_exclude_patterns=["/contact", "/news", "/events", "/servicos", "/gabinete"],
    ),
    SourceDefinition(
        key="ipvc_research",
        name="IPVC Research & Innovation",
        url="https://www.ipvc.pt/en/investigacao/",
        organization_token="ipvc",
        target_profile="researcher",
        country="PT",
        domain_names=["AI", "Digitalisation"],
        enabled=False,  # 404 — English research URL not found
        crawl_enabled=True,
        crawl_depth=2,
        crawl_match_patterns=["/en/investigacao/", "/en/research/"],
        crawl_exclude_patterns=["/contact", "/news", "/events", "/servicos", "/gabinete"],
    ),
]


def get_sources(source_keys: list[str] | None = None) -> list[SourceDefinition]:
    from content.models import ScrapingSource  # local import avoids circular dep

    qs = ScrapingSource.objects.all()
    if source_keys:
        qs = qs.filter(key__in=source_keys)
    else:
        qs = qs.filter(enabled=True)

    return [
        SourceDefinition(
            key=s.key,
            name=s.name,
            url=s.url,
            organization_token=s.organization_token,
            target_profile=s.target_profile,
            country=s.country,
            domain_names=s.domain_names,
            interval_minutes=s.interval_minutes,
            llm_fallback_enabled=s.llm_fallback_enabled,
            enabled=s.enabled,
            quality=s.quality,
            crawl_enabled=s.crawl_enabled,
            crawl_depth=s.crawl_depth,
            crawl_max_pages=s.crawl_max_pages,
            crawl_match_patterns=s.crawl_match_patterns,
            crawl_exclude_patterns=s.crawl_exclude_patterns,
        )
        for s in qs
    ]
