from content.scrapers.types import SourceDefinition

# One seed per partner university. All disabled by default — enable via admin UI or API.
# Crawl settings are pre-configured; just flip `enabled=True` to start scraping.
SOURCE_REGISTRY: list[SourceDefinition] = [
    SourceDefinition(
        key="unibz",
        name="Free University of Bozen-Bolzano",
        url="https://www.unibz.it/",
        organization_token="unibz",
        target_profile="student",
        country="IT",
        domain_names=["Digitalisation", "AI"],
        enabled=False,
        crawl_enabled=True,
        crawl_depth=3,
        crawl_max_pages=100,
        crawl_match_patterns=["/en/", "/faculties/", "/applicants/"],
        crawl_exclude_patterns=[
            "/en/home/", "/news", "/events", "/contact", "/alumni",
            "/sustainability", "/quality-assurance", "/assignments",
            "/position-calls", "/5x1000", "/companies-and-partnerships",
        ],
    ),
    SourceDefinition(
        key="mdu",
        name="Mälardalen University",
        url="https://www.mdu.se/",
        organization_token="mdu",
        target_profile="student",
        country="SE",
        domain_names=["Robotics", "AI", "Digitalisation"],
        enabled=False,
        crawl_enabled=True,
        crawl_depth=3,
        crawl_max_pages=100,
        crawl_match_patterns=["/en/", "/forskning", "/utbildning"],
        crawl_exclude_patterns=[
            "/contact", "/news", "/events", "/login", "/apply",
            "/nyheter", "/evenemang", "/alumni", "/press", "/donate",
            "/calendar", "/konferens",
        ],
    ),
    SourceDefinition(
        key="tu_ilmenau",
        name="TU Ilmenau",
        url="https://www.tu-ilmenau.de/",
        organization_token="tu_ilmenau",
        target_profile="student",
        country="DE",
        domain_names=["AI", "Digitalisation"],
        enabled=False,
        crawl_enabled=True,
        crawl_depth=3,
        crawl_max_pages=100,
        crawl_match_patterns=["/en/", "/studium/studiengaenge", "/forschung/"],
        crawl_exclude_patterns=[
            "/studium/vor-dem-studium", "/news", "/events", "/presse",
            "/veranstaltungen", "/forschung-international/sunrise",
        ],
    ),
    SourceDefinition(
        key="utc",
        name="Université de Technologie de Compiègne",
        url="https://www.utc.fr/",
        organization_token="utc",
        target_profile="student",
        country="FR",
        domain_names=["Digitalisation", "AI"],
        enabled=False,
        crawl_enabled=True,
        crawl_depth=3,
        crawl_max_pages=100,
        crawl_match_patterns=["/en/", "/formation", "/recherche"],
        crawl_exclude_patterns=[
            "/contact", "/news", "/events", "/login", "/apply",
            "/actualites", "/agenda", "/alumni", "/presse",
        ],
    ),
    SourceDefinition(
        key="euc",
        name="European University Cyprus",
        url="https://www.euc.ac.cy/",
        organization_token="euc",
        target_profile="student",
        country="CY",
        domain_names=["Digitalisation", "AI"],
        enabled=False,
        crawl_enabled=True,
        crawl_depth=3,
        crawl_max_pages=100,
        crawl_match_patterns=["/en/programs", "/en/research", "/en/schools", "/en/faculties"],
        crawl_exclude_patterns=["/contact", "/apply", "/login", "/news", "/events", "/gallery"],
    ),
    SourceDefinition(
        key="uitm",
        name="University of Information Technology and Management",
        url="https://www.uitm.edu.eu/",
        organization_token="uitm",
        target_profile="student",
        country="PL",
        domain_names=["Digitalisation", "AI"],
        enabled=False,
        crawl_enabled=True,
        crawl_depth=3,
        crawl_max_pages=100,
        crawl_match_patterns=["/en/", "/study", "/research"],
        crawl_exclude_patterns=[
            "/contact", "/news", "/events", "/login", "/apply",
            "/gallery", "/awards", "/alumni", "/press", "/donate",
        ],
    ),
    SourceDefinition(
        key="univpm",
        name="Università Politecnica delle Marche",
        url="https://www.univpm.it/",
        organization_token="univpm",
        target_profile="student",
        country="IT",
        domain_names=["Digitalisation", "AI"],
        enabled=False,
        crawl_enabled=True,
        crawl_depth=3,
        crawl_max_pages=100,
        crawl_match_patterns=["/Entra/", "/Didattica", "/Ricerca"],
        crawl_exclude_patterns=["/Notizie", "/Calendario", "/Contatti", "/HR_Excellence"],
    ),
    SourceDefinition(
        key="unmo",
        name="University of Mostar",
        url="https://www.unmo.ba/",
        organization_token="unmo",
        target_profile="student",
        country="BA",
        domain_names=["Digitalisation"],
        enabled=False,
        crawl_enabled=True,
        crawl_depth=2,
        crawl_max_pages=50,
        crawl_match_patterns=["/en/", "/nastava", "/istrazivanje"],
        crawl_exclude_patterns=["/contact", "/news", "/events", "/login", "/apply", "/vijesti"],
    ),
    SourceDefinition(
        key="ipvc",
        name="Instituto Politécnico de Viana do Castelo",
        url="https://www.ipvc.pt/",
        organization_token="ipvc",
        target_profile="student",
        country="PT",
        domain_names=["Digitalisation"],
        enabled=False,
        crawl_enabled=True,
        crawl_depth=3,
        crawl_max_pages=100,
        crawl_match_patterns=["/en/", "/cursos", "/investigacao"],
        crawl_exclude_patterns=[
            "/contact", "/news", "/events", "/login", "/apply",
            "/noticias", "/agenda", "/alumni", "/imprensa",
            "/sobre-o-ipvc/", "/organizacao/", "/orcamento",
            "/contratos-publicos", "/projetos-institucionais",
            "/servicos/", "/escolas-ipvc/", "/gabinete", "/clipping",
        ],
    ),
]


def get_sources(source_keys: list[str] | None = None) -> list[SourceDefinition]:
    from content.models import ScrapingSource  # local import avoids circular dep

    qs = ScrapingSource.objects.all()
    if source_keys:
        qs = qs.filter(key__in=source_keys)
    else:
        qs = qs.filter(enabled=True)

    return [
        SourceDefinition(
            key=s.key,
            name=s.name,
            url=s.url,
            organization_token=s.organization_token,
            organization_id=str(s.organization_id) if s.organization_id else None,
            target_profile=s.target_profile,
            country=s.country,
            domain_names=s.domain_names,
            interval_minutes=s.interval_minutes,
            llm_fallback_enabled=s.llm_fallback_enabled,
            enabled=s.enabled,
            quality=s.quality,
            crawl_depth=s.crawl_depth,
            crawl_max_pages=s.crawl_max_pages,
            crawl_match_patterns=s.crawl_match_patterns,
            crawl_exclude_patterns=s.crawl_exclude_patterns,
        )
        for s in qs
    ]
