from content.scrapers.types import SourceDefinition


SOURCE_REGISTRY: list[SourceDefinition] = [
    SourceDefinition(
        key="unibz_master_software_engineering",
        name="UNIBZ Master in Software Engineering",
        url="https://www.unibz.it/en/faculties/engineering/master-software-engineering/",
        organization_token="unibz",
        offer_type="training",
        target_profile="student",
        country="IT",
        domain_names=["AI", "Digitalisation", "Technology_transfer"],
    ),
    SourceDefinition(
        key="unibz_phd_computer_science",
        name="UNIBZ PhD in Computer Science",
        url="https://www.unibz.it/en/faculties/engineering/phd-computer-science/",
        organization_token="unibz",
        offer_type="training",
        target_profile="researcher",
        country="IT",
        domain_names=["AI", "Digitalisation"],
    ),
    SourceDefinition(
        key="unibz_bachelor_computer_science",
        name="UNIBZ Bachelor in Computer Science",
        url="https://www.unibz.it/en/faculties/engineering/bachelor-computer-science/",
        organization_token="unibz",
        offer_type="training",
        target_profile="student",
        country="IT",
        domain_names=["Digitalisation", "Cybersecurity"],
    ),
    SourceDefinition(
        key="unibz_erasmus_mobility",
        name="UNIBZ International Mobility",
        url="https://www.unibz.it/en/applicants/international/",
        organization_token="unibz",
        offer_type="training",
        target_profile="student",
        country="IT",
        domain_names=["Mobility", "Digitalisation"],
    ),
    SourceDefinition(
        key="mdu_fas_licentiate_thesis",
        name="MDU Research Schools Thesis Track",
        url="https://www.mdu.se/en/malardalen-university/research/research-schools",
        organization_token="mdu",
        offer_type="thesis",
        target_profile="researcher",
        country="SE",
        domain_names=["Robotics", "AI"],
    ),
    SourceDefinition(
        key="mdu_embedded_systems_research_group",
        name="MDU Embedded Systems Research Group",
        url="https://www.mdu.se/en/malardalen-university/research/research-specialisations/embedded-systems",
        organization_token="mdu",
        offer_type="research_group",
        target_profile="researcher",
        country="SE",
        domain_names=["Robotics", "AI"],
    ),
    SourceDefinition(
        key="mdu_din_funding_partner",
        name="MDU DIN Funding Partner",
        url="https://www.mdu.se/en/malardalen-university/research/research-specialisations/innovation-and-product-realisation",
        organization_token="mdu",
        offer_type="funding_partner",
        target_profile="company",
        country="SE",
        domain_names=["Technology_transfer", "Innovation_and_entrepreneurship"],
    ),
    SourceDefinition(
        key="tu_ilmenau_crawler_seed",
        name="TU Ilmenau Crawler Seed",
        url="https://www.tu-ilmenau.de/",
        organization_token="tu_ilmenau",
        offer_type="training",
        target_profile="student",
        country="DE",
        domain_names=["Digitalisation"],
        enabled=True,
        crawl_enabled=True,
        crawl_match_patterns=["/en/", "/studium/studiengaenge", "/forschung/"],
        crawl_exclude_patterns=["/studium/vor-dem-studium", "/news", "/events", "/presse", "/veranstaltungen", "/forschung-international/sunrise"],
    ),
    SourceDefinition(
        key="unibz_crawler_seed",
        name="UNIBZ Crawler Seed",
        url="https://www.unibz.it/",
        organization_token="unibz",
        offer_type="training",
        target_profile="student",
        country="IT",
        domain_names=["Digitalisation"],
        enabled=True,
        crawl_enabled=True,
        crawl_match_patterns=["/en/", "/faculties/", "/applicants/"],
        crawl_exclude_patterns=[
            "/en/home/",
            "/news", "/events", "/contact", "/alumni",
            "/sustainability", "/quality-assurance",
            "/assignments", "/position-calls", "/5x1000",
            "/companies-and-partnerships",
        ],
    ),
    SourceDefinition(
        key="uitm_crawler_seed",
        name="UITM Crawler Seed",
        url="https://www.uitm.edu.eu/",
        organization_token="uitm",
        offer_type="training",
        target_profile="student",
        country="PL",
        domain_names=["Digitalisation"],
        enabled=True,
        crawl_enabled=True,
        crawl_match_patterns=["/en/", "/study", "/research"],
        crawl_exclude_patterns=["/contact", "/news", "/events", "/login", "/apply", "/gallery", "/awards", "/alumni", "/press", "/donate"],
    ),
    SourceDefinition(
        key="utc_crawler_seed",
        name="UTC Crawler Seed",
        url="https://www.utc.fr/",
        organization_token="utc",
        offer_type="training",
        target_profile="student",
        country="FR",
        domain_names=["Digitalisation"],
        enabled=True,
        crawl_enabled=True,
        crawl_match_patterns=["/en/", "/formation", "/recherche"],
        crawl_exclude_patterns=["/contact", "/news", "/events", "/login", "/apply", "/actualites", "/agenda", "/alumni", "/presse"],
    ),
    SourceDefinition(
        key="euc_crawler_seed",
        name="European University Cyprus Crawler Seed",
        url="https://www.euc.ac.cy/",
        organization_token="euc",
        offer_type="training",
        target_profile="student",
        country="CY",
        domain_names=["Digitalisation"],
        enabled=True,
        crawl_enabled=True,
        crawl_match_patterns=["/en/programs", "/en/research", "/en/schools", "/en/faculties"],
        crawl_exclude_patterns=["/contact", "/apply", "/login", "/news", "/events", "/gallery", "/awards", "/recognition"],
    ),
    SourceDefinition(
        key="mdu_crawler_seed",
        name="MDU Crawler Seed",
        url="https://www.mdu.se/",
        organization_token="mdu",
        offer_type="training",
        target_profile="student",
        country="SE",
        domain_names=["Digitalisation"],
        enabled=True,
        crawl_enabled=True,
        crawl_match_patterns=["/en/", "/forskning", "/utbildning"],
        crawl_exclude_patterns=["/contact", "/news", "/events", "/login", "/apply", "/nyheter", "/evenemang", "/alumni", "/press", "/donate"],
    ),
    SourceDefinition(
        key="univpm_crawler_seed",
        name="UNIVPM Crawler Seed",
        url="https://www.univpm.it/",
        organization_token="univpm",
        offer_type="training",
        target_profile="student",
        country="IT",
        domain_names=["Digitalisation"],
        enabled=True,
        crawl_enabled=True,
        crawl_match_patterns=["/En/", "/Didattica", "/Ricerca"],
        crawl_exclude_patterns=["/Contact", "/News", "/Events", "/Login", "/Apply", "/Notizie", "/Calendario", "/Alumni", "/Press"],
    ),
    SourceDefinition(
        key="unmo_crawler_seed",
        name="UNMO Crawler Seed",
        url="https://www.unmo.ba/",
        organization_token="unmo",
        offer_type="training",
        target_profile="student",
        country="BA",
        domain_names=["Digitalisation"],
        enabled=True,
        crawl_enabled=True,
        crawl_match_patterns=["/en/", "/nastava", "/istrazivanje"],
        crawl_exclude_patterns=["/contact", "/news", "/events", "/login", "/apply", "/vijesti", "/alumni", "/press"],
    ),
    SourceDefinition(
        key="ipvc_crawler_seed",
        name="IPVC Crawler Seed",
        url="https://www.ipvc.pt/",
        organization_token="ipvc",
        offer_type="training",
        target_profile="student",
        country="PT",
        domain_names=["Digitalisation"],
        enabled=True,
        crawl_enabled=True,
        crawl_match_patterns=["/en/", "/cursos", "/investigacao"],
        crawl_exclude_patterns=[
            "/contact", "/news", "/events", "/login", "/apply",
            "/noticias", "/agenda", "/alumni", "/imprensa",
            "/sobre-o-ipvc/", "/organizacao/",
            "/orcamento", "/contratos-publicos", "/projetos-institucionais",
        ],
    ),
]


def get_sources(source_keys: list[str] | None = None) -> list[SourceDefinition]:
    if not source_keys:
        return [source for source in SOURCE_REGISTRY if source.enabled]

    source_key_set = set(source_keys)
    return [
        source
        for source in SOURCE_REGISTRY
        if source.key in source_key_set
    ]
