from django.urls import path

from content import views

urlpatterns = [
    path("", views.api_docs, name="api-docs-home"),
    path("docs", views.api_docs, name="api-docs"),
    path("redoc", views.redoc_docs, name="api-redoc"),
    path("openapi.json", views.openapi_schema, name="openapi-schema"),
    path("health", views.health, name="health"),
    path("scraping/runs", views.scraping_runs, name="scraping-runs"),
    path("scraping/runs/<str:run_id>", views.scraping_run_detail, name="scraping-run-detail"),
    path("scraping/overview", views.scraping_overview, name="scraping-overview"),
    path("scraping/sources/health", views.scraping_sources_health, name="scraping-sources-health"),
    path("scraping/llm/stats", views.scraping_llm_stats, name="scraping-llm-stats"),
    path("lookups/offer-types", views.offer_types, name="offer-types"),
    path("lookups/domains", views.domains, name="domains"),
    path("lookups/organizations", views.organizations, name="organizations"),
    path("lookups/target-profiles", views.target_profiles, name="target-profiles"),
    path("lookups/countries", views.countries, name="countries"),
    path("users", views.upsert_user, name="upsert-user"),
    path("users/<str:user_id>", views.user_resource, name="user-detail"),
    path("users/<str:user_id>/organizations", views.link_user_organization, name="link-user-organization"),
    path("users/<str:user_id>/organizations/<str:org_id>", views.unlink_user_organization, name="unlink-user-organization"),
    path("users/<str:user_id>/dashboard", views.dashboard, name="user-dashboard"),
    path("users/<str:user_id>/needs", views.user_needs, name="user-needs"),
    path("users/<str:user_id>/needs/<str:need_id>", views.user_need_detail, name="user-need-detail"),
    path("users/<str:user_id>/favorites", views.user_favorites, name="user-favorites"),
    path("users/<str:user_id>/favorites/<str:offer_id>", views.user_favorite_detail, name="user-favorite-detail"),
    path("users/<str:user_id>/matching-hits", views.user_matching_hits, name="user-matching-hits"),
    path("users/<str:user_id>/matching-hits/<str:hit_id>", views.user_matching_hit_detail, name="user-matching-hit-detail"),
    path("offers/import/template", views.import_template, name="import-template"),
    path("offers/import/preview", views.import_preview, name="import-preview"),
    path("offers/import/confirm", views.import_confirm, name="import-confirm"),
    path("offers", views.offers, name="offers"),
    path("offers/<str:offer_id>", views.offer_detail, name="offer-detail"),
]
